name: Stale

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@main
        id: stale
        with:
          exempt-issue-labels: "no-stale"
          days-before-stale: 14
          days-before-close: 3
          remove-issue-stale-when-updated: true
          remove-pr-stale-when-updated: true
          labels-to-remove-when-unstale: "stale"
          stale-issue-message: "This issue is stale because it has been open for 14 days with no activity. This issue will be marked as stale in 3 days."
          close-issue-message: "This issue has been marked as stale."
          stale-pr-message: "This pull request is stale because it has been open for 14 days with no activity. This pull request will be marked as stale in 3 days."
          close-pr-message: "This pull request has been marked as stale."
